Web/Controllers/LeavesController.cs
using Library;
using Library.Model;
using MVC_CustomActionFilter.Helper;
using NHibernateDemo.Repositories;
using NHibernateDemo.Repositories.Imp;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class LeavesController : Controller
    {
        private readonly ILeaveRepository _repository;

        public LeavesController(ILeaveRepository repository)
        {
            _repository = repository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Policy()
        {
            return View();
        }

        public ActionResult NewRequest()
        {
            //TODO
            return View();
        }

        public ActionResult Summary()
        {            
            return View(_repository.GetList());
        }
    }
}

Web/Controllers/TimmingsController.cs
using Library;
using Library.Model;
using MVC_CustomActionFilter.Helper;
using NHibernateDemo.Repositories;
using NHibernateDemo.Repositories.Imp;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    //TODO: will be double check late
    [CustomAuthFilter]
    [CustomExceptionFilter]
    public class TimmingsController : Controller
    {
        private readonly ITimmingRepository _repository;

        public TimmingsController(ITimmingRepository repository)
        {
            _repository = repository;
        }

        //TODO
        //[Route("Timming/Index123/{userId}")]
        public ActionResult Index(string userId)
        {
            return View(_repository.GetById(userId));
        }
    }
}

Web/Controllers/UsersController.cs
using Library;
using Library.Model;
using MVC_CustomActionFilter.Helper;
using NHibernateDemo.Repositories;
using NHibernateDemo.Repositories.Imp;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserRepository _repository;

        public UsersController(IUserRepository repository)
        {
            _repository = repository;
        }

        public ActionResult Login()
        {
            //Check in a user will be logout
            if (UserRepository.isLogin == true)
            {
                SessionManager.CloseSession();
                UserRepository.isLogin = false;
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(User user)
        {
            User oldUser = _repository.GetByEmail(user.EmailAddr);
            if (user.EmailAddr == oldUser.EmailAddr && user.PassWord == oldUser.PassWord)
            {
                UserRepository.isLogin = true;
                Session["fullName"] = oldUser.LastName + " " + oldUser.FirstName;
                Session["userId"] = oldUser.UserId;

                return RedirectToAction("Details/" + oldUser.UserId);
            }

            return View();
        }   

        [CustomAuthFilter]
        [CustomExceptionFilter]
        public ActionResult Details(string id)
        {
            return View(_repository.GetById(id));
        }

        public ActionResult Edit(string id)
        {
            return View(_repository.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                _repository.Update(user);
                Session["fullName"] = user.LastName + " " + user.FirstName;
                return RedirectToAction("Details/" + user.UserId);
            }
            return View(user);
        }
    }
}

Web/Views/Leaves/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p align="left">
    @Html.ActionLink("New Request", "NewRequest")
</p>
<p align="right">
    @Html.ActionLink("Summary", "Summary")
</p>

Web/Views/Leaves/NewRequest.cshtml
@model Library.Model.User

@{
    ViewBag.Title = "New Request";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js"></script>

<style>
    #startDate {
        position: relative;
        width: 150px;
        height: 30px;
        color: white;
    }

        #startDate:before {
            position: absolute;
            top: 3px;
            left: 3px;
            content: attr(data-date);
            display: inline-block;
            color: black;
        }

        #startDate::-webkit-datetime-edit, #startDate::-webkit-inner-spin-button, #startDate::-webkit-clear-button {
            display: none;
        }

        #startDate::-webkit-calendar-picker-indicator {
            position: absolute;
            top: 3px;
            right: 0;
            color: black;
            opacity: 1;
        }

            #endDate {
        position: relative;
        width: 150px;
        height: 30px;
        color: white;
    }

        #endDate:before {
            position: absolute;
            top: 3px;
            left: 3px;
            content: attr(data-date);
            display: inline-block;
            color: black;
        }

        #endDate::-webkit-datetime-edit, #endDate::-webkit-inner-spin-button, #endDate::-webkit-clear-button {
            display: none;
        }

        #endDate::-webkit-calendar-picker-indicator {
            position: absolute;
            top: 3px;
            right: 0;
            color: black;
            opacity: 1;
        }
</style>

<h2>Apply Leave</h2>

<hr />

<p align="right">
    @Html.ActionLink("Leave Policy", "Policy")
</p>
<table>
    <tr>
        <td>
            Type of Leave*: 
        </td>
        <td>
            <select>
                <option value="Annual Leave">---Select---</option>
                <option value="Annual Leave">Annual Leave</option>
                <option value="Business Reason">Business Reason</option>
                <option value="Birthday Leave">Birthday Leave</option>
                <option value="Children Care">Children Care</option>
                <option value="Sick Leave">Sick Leave</option>
            </select>
        </td>
    </tr>
    <tr>
        <td>
            Start Date*:
        </td>
        <td><input id="startDate" type="date" data-date-format="DD MMMM YYYY"></td>
    </tr>
    <tr>
        <td>
            End Date*:
        </td>
        <td><input id="endDate" type="date" data-date-format="DD MMMM YYYY"></td>
    </tr>
    @*<tr>
        <td>
            Absent Days:
        </td>
        <td>
            DropDown
        </td>
    </tr>*@
    <tr>
        <td>
            Comments:
        </td>
        <td>
            <textarea style="width: 400px; height: 150px">

            </textarea>
        </td>
    </tr>
    <tr>
        <td>
            Attachment:
        </td>
        <td>
            <input type="file" value="csd" /> <br/>
        </td>
    </tr>
    <tr>
        <td>
        </td>
        <td>
            <p style="color:red">(Maximize file size up to 15MB)</p>
        </td>
    </tr>
</table>
<input type="button" value="Attach" />
<br />
<div>
    <input type="button" value="Submit" />
    <input type="button" value="Reset" />
    <input type="button" value="Back" />
</div>

<script>
            //Set init time
        $('#startDate').val(moment().format('YYYY-MM-DD'));

    $("#startDate").on("change", function () {
            this.setAttribute("data-date", moment(this.value, "YYYY-MM-DD").format(this.getAttribute("data-date-format")))

    }).trigger("change")

    $('#endDate').val(moment().format('YYYY-MM-DD'));

    $("#endDate").on("change", function () {
        this.setAttribute("data-date", moment(this.value, "YYYY-MM-DD").format(this.getAttribute("data-date-format")))

    }).trigger("change")
</script>

Web/Views/Leaves/Summary.cshtml
@model IEnumerable<Library.Model.LeaveRequest>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Summary</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LeaveRequestId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeOfLeave)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LeaveDescription)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LeaveRequestId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeOfLeave)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FromDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ToDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LeaveDescription)
            </td>
        </tr>
    }

</table>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Leave Tool", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Leave", "Index", "Leaves")</li>
                    <li>@Html.ActionLink("User Profile", "Details", "Users", new { id = (string)Session["userId"] }, null)</li>
                    <li>@Html.ActionLink("Timming", "Index", "Timmings", new { userId = (string)Session["userId"] }, null)</li>
                </ul>
                @Html.Partial("_LogoutPartial", (string)Session["fullName"])
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Web/Views/Shared/_LogoutPartial.cshtml
<ul class="nav navbar-nav navbar-right">
    <li style="color: #FFFFFF; padding-top: 15px;">Hello @Model</li> 
    <li>@Html.ActionLink("Log out", "Login", "Users", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
</ul>

Web/Views/Timmings/Index.cshtml
@model IEnumerable<Library.Model.Timming>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Day)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeIn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeOut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comments)
        </th>
        @*<th>
            Tools
        </th>*@
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Day)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TimeIn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TimeOut)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comments)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ManufacturerID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ManufacturerID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ManufacturerID })
        </td>*@
    </tr>
}

</table>

Web/Views/Users/Details.cshtml
@model Library.Model.User

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Manage Personal Information</h2>

<div>
    <hr />
    <p align=RIGHT>
        @Html.ActionLink("Modify", "Edit", new { id = Model.UserId })
    </p>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EmailAddr)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmailAddr)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContactPhone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContactPhone)
        </dd>
    </dl>
</div>

Web/Views/Users/Edit.cshtml
@model Library.Model.User

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Manage Personal Information</h2>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js"></script>

<style>
    [type~=date] {
        position: relative;

        width: 150px;
        height: 30px;
        color: white;
    }

        [type~=date]:before {
            position: absolute;
            top: 3px;
            left: 3px;
            content: attr(data-date);
            display: inline-block;
            color: black;
        }

        [type~=date]::-webkit-datetime-edit, [type~=date]::-webkit-inner-spin-button, [type~=date]::-webkit-clear-button {
            display: none;
        }

        [type~=date]::-webkit-calendar-picker-indicator {
            position: absolute;
            top: 3px;
            right: 0;
            color: black;
            opacity: 1;
        }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.DayOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="birthDate" type="date" data-date-format="DD MMMM YYYY">
                @Html.HiddenFor(model => model.DayOfBirth)
            </div>
            @Html.LabelFor(model => model.JoinDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="joinDate" type="date" data-date-format="DD MMMM YYYY">
                @Html.HiddenFor(model => model.JoinDate)
            </div>
            @Html.LabelFor(model => model.ContactPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactPhone, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>

            <!--If change a email or password auto logout to login page-->
            @Html.LabelFor(model => model.EmailAddr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddr, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.PassWord, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PassWord, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
            </div>
            
            @Html.HiddenFor(model => model.Holiday.HolidayId)
            @Html.HiddenFor(model => model.Possition)
            @Html.HiddenFor(model => model.Level)
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Details/" + @Model.UserId)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $(document).ready(function () {
        var birthDate = @Html.Raw(Json.Encode(Model.DayOfBirth.ToString("yyyy-MM-dd")));
        var joinDate = @Html.Raw(Json.Encode(Model.JoinDate.ToString("yyyy-MM-dd")));

        //Set init time
        $('#birthDate').val(birthDate);
        $('#joinDate').val(joinDate);

        $("#joinDate").on("change", function () {
            this.setAttribute("data-date", moment(this.value, "YYYY-MM-DD").format(this.getAttribute("data-date-format")))
            $("#JoinDate").val($('#joinDate').val());
        }).trigger("change")

        $("#birthDate").on("change", function () {
            this.setAttribute("data-date", moment(this.value, "YYYY-MM-DD").format(this.getAttribute("data-date-format")))
            $("#DayOfBirth").val($('#birthDate').val());
        }).trigger("change")
    });
</script>

Web/Views/Users/Login.cshtml
@model Library.Model.User
@{
    ViewBag.Title = "Log in";
    Layout = "";
}

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Users", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Use a local account to log in.</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    Email
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.EmailAddr, new { @class = "form-control", @required = "required" })
                    </div>
                </div>
                <div class="form-group">
                    Password
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.PassWord, new { @class = "form-control", @required = "required" })
                    </div>
                </div>
                @*<div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.RememberMe)
                            @Html.LabelFor(m => m.RememberMe)
                        </div>
                    </div>
                </div>*@
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                @* Enable this once you have account confirmation enabled for password reset functionality
                    <p>
                        @Html.ActionLink("Forgot your password?", "ForgotPassword")
                    </p>*@
            }
        </section>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}